#!/bin/sh
rm -rf "$INSTALL_PATH/3rdparty_licenses"
rm -rf "$INSTALL_PATH/ant"
rm -rf "$INSTALL_PATH/db"
rm -rf "$INSTALL_PATH/docs"
rm -rf "$INSTALL_PATH/logs"
rm -rf "$INSTALL_PATH/osdependent"
rm -rf "$INSTALL_PATH/remoting"
rm -rf "$INSTALL_PATH/scripts"
rm -rf "$INSTALL_PATH/tmp"
rm -rf "$INSTALL_PATH/Uninstaller"
rm -rf "$INSTALL_PATH/web"
rm -rf "$INSTALL_PATH/wrapper_sample"
rm -f "$INSTALL_PATH/luntbuild.war"
rm -f "$INSTALL_PATH/readme.txt"
rm -f "$INSTALL_PATH/feature_list.txt"
