rmdir /S /Q "$INSTALL_PATH\3rdparty_licenses"
rmdir /S /Q "$INSTALL_PATH\ant"
rmdir /S /Q "$INSTALL_PATH\db"
rmdir /S /Q "$INSTALL_PATH\docs"
rmdir /S /Q "$INSTALL_PATH\logs"
rmdir /S /Q "$INSTALL_PATH\osdependent"
rmdir /S /Q "$INSTALL_PATH\remoting"
rmdir /S /Q "$INSTALL_PATH\scripts"
rmdir /S /Q "$INSTALL_PATH\tmp"
rmdir /S /Q "$INSTALL_PATH\Uninstaller"
rmdir /S /Q "$INSTALL_PATH\web"
rmdir /S /Q "$INSTALL_PATH\wrapper_sample"
del /F "$INSTALL_PATH\luntbuild.jar"
del /F "$INSTALL_PATH\readme.txt"
del /F "$INSTALL_PATH\feature_list.txt"